In [2]:
#THis is PCA done using eigh function
import numpy as np

In [3]:
# Assume there are 5 movies  and 7 users
#Movies are "Matrix, ALien, Serenity, Casablanca, Amelie",users are u1,u2,u3,u4, u5, u6, u7
#UserMovies capture the ratings given by each user on a movie
UserMovies= np.array([[1, 1, 1, 0, 0], 
                      [3,3,3,0,0],
                     [4,4,4,0,0],
                     [5,5,5,0,0],
                     [0,2,0,4,4],
                     [0,0,0, 5,5],
                     [0,1,0,2,2]])
#Um = np.dot(UserMovies, UserMovies.T)
Um = UserMovies
Um = Um/ 7
print (UserMovies.shape)
# UmCov = np.dot(Um,Um.T)
UmCov = np.dot(Um.T,Um)
print (UmCov.shape)

(7, 5)
(5, 5)


In [4]:
#Lets find the Eigenvectors and eigenvalues of UmCov
eig_val_u, eig_vect_u = np.linalg.eig(UmCov)
eig_val_u, eig_vect_u = np.round(eig_val_u,2), np.round(eig_vect_u,2)
print ("eig_vect_u.shape=",eig_vect_u.shape, "\neig_vect=\n", eig_vect_u)
print ("eig_val_u.shape=",eig_val_u.shape, "\neig_val_u=\n", eig_val_u)

eig_vect_u.shape= (5, 5) 
eig_vect=
 [[ 0.56  0.13 -0.71 -0.41  0.  ]
 [ 0.59 -0.03  0.    0.8   0.  ]
 [ 0.56  0.13  0.71 -0.41  0.  ]
 [ 0.09 -0.7  -0.   -0.09 -0.71]
 [ 0.09 -0.7  -0.   -0.09  0.71]]
eig_val_u.shape= (5,) 
eig_val_u=
 [3.18 1.85 0.   0.04 0.  ]


In [5]:
#Lets see what is the variance we will get if we take 2 columns:

print ("Variance Captured via eig=",(eig_val_u[0]+eig_val_u[1])/np.sum(eig_val_u))
print (np.sum(eig_val_u))


Variance Captured via eig= 0.9921104536489151
5.07


In [7]:
#Lets take the 2 columns and extract the vectors corresponding to those columns and find the modified values
#Eig way
ZEig_2 = eig_vect_u[:,:2]
print (ZEig_2.shape, Um.shape)
# XEig_2 = np.dot(UmCov, ZEig_2)
XEig_2 = np.dot(Um, ZEig_2)
XEig_2 = np.round(XEig_2, 3)
print (Um.shape, ZEig_2.shape, XEig_2.shape)
print("XReduced=\n", XEig_2)

(5, 2) (7, 5)
(7, 5) (5, 2) (7, 2)
XReduced=
 [[ 0.244  0.033]
 [ 0.733  0.099]
 [ 0.977  0.131]
 [ 1.221  0.164]
 [ 0.271 -0.809]
 [ 0.129 -1.   ]
 [ 0.136 -0.404]]


In [8]:
#Lets take the 3 columns and extract the vectors corresponding to those columns and find the modified values
#Eig way
#Lets find the sum of variances we will retain if we take 3 columns

print ("Variance Captured via eig=",(eig_val_u[0]+eig_val_u[1]+eig_val_u[2])/np.sum(eig_val_u))
print (np.sum(eig_val_u))
ZEig_3 = eig_vect_u[:,:3]
# XEig_3 = np.dot(UmCov, ZEig_3)
XEig_3 = np.dot(Um, ZEig_3)
XEig_3 = np.round(XEig_3, 3)
print (UmCov.shape, ZEig_3.shape, XEig_3.shape)
print("XReduced=\n", XEig_3)

Variance Captured via eig= 0.9921104536489151
5.07
(5, 5) (5, 3) (7, 3)
XReduced=
 [[ 0.244  0.033 -0.   ]
 [ 0.733  0.099 -0.   ]
 [ 0.977  0.131 -0.   ]
 [ 1.221  0.164  0.   ]
 [ 0.271 -0.809  0.   ]
 [ 0.129 -1.     0.   ]
 [ 0.136 -0.404  0.   ]]


In [10]:
#We have reduced the original (7, 5) to (7,2), and (7,3) using PCA
# We can imagine that the 5 movies represent concepts and we have captured those into 2 concepts. We can call them as genres
#It so happens that there are only 3 dominant genres in this dataset :-) Is it "Action", "Romance" and "Scifi"